config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :appointments
  resources :exercises
  resources :bodyareas
  resources :typesofexercises
  resources :reminders, only: [:new, :create, :destroy]

  root "static_pages#home"


end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  has_many :appointments_exercises
  has_many :exercises, through: :appointments_exercises
  has_many :users_appointments
  has_many :users, through: :users_appointments

  validates :app_date, presence: true

  accepts_nested_attributes_for :exercises

  def start_time
    self.app_date
  end

  def name   
    string = ""

    if self.exercises.any?
      self.exercises.each do |exercise|
        if string.empty?
          string = exercise.typesofexercise.name
        else
          string = string + " + " + exercise.typesofexercise.name
        end
      end
    end

    name = string
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :find_appointment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @appointments = User.find_by_id(current_user).appointments
    @bodyareas = Bodyarea.all

    respond_to do |format|
      format.html
      format.js
    end  
  end  

  def show
  end

  def new
    @appointment = Appointment.new
    @bodyareas = Bodyarea.all
    @exercise = Exercise.new
    @appointment.exercises.build()
  end

  def create
    @appointment = Appointment.new(appointment_params)

    binding.pry

    if @appointment.save
      flash[:notice] = "The appointment was saved successfully!"

      redirect_to appointments_path
    else
      render :new
    end
  end

  def edit
    @bodyareas = Bodyarea.all
  end

  def update
    if @appointment.update(appointment_params)
      flash[:notice] = "The appointment was updated successfully"

      redirect_to appointments_path
    else
      render :edit
    end
  end

  def find_appointment
    @appointment = Appointment.find_by_id(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:app_date, :duration, :comments, :exercises_attributes => [:id, :n_of_sets, :n_of_repetitions, :duration_of_repetition, :bodyarea_id, :typesofexercise_id], :exercise_ids => [], :user_ids => []).merge(user_ids: current_user.id)
  end
end  

app/views/appointments/_exercise_fields.html.erb
<fieldset>
  <div class="form-group">
    <p>Select the body area:</p>
    <%= f.label :bodyarea_id %>
    <%= f.collection_select(:bodyarea_id, Bodyarea.all, :id, :name, { include_blank: true }, { class: "bodyarea_select"}) %>
  </div>

  <div  class="form-group">
    <%= f.label :typesofexercise_id %>
    <%= f.grouped_collection_select(:typesofexercise_id, Bodyarea.all, :typesofexercises, :name,  :id, :name, { include_blank: true }) %>  
  </div>

  <div class="form-group">
    <%= f.label :sets %>
    <%= f.text_field :n_of_sets, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :repetitions %>
    <%= f.text_field :n_of_repetitions, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :duration_of_repetitions %>
    <%= f.text_field :duration_of_repetition, class: "form-control" %>
  </div>
</fieldset>

app/views/appointments/_form.html.erb
<%= form_for(@appointment, { remote: true } ) do |f| %>

  <div class="form-group">
    <%= f.datetime_select :app_date %>
  </div>

  <div class="form-group">
    <%= f.label :duration %>
    <%= f.text_field :duration %>
  </div>

  <div class="form-group">
    <%= f.label :comments %>
    <%= f.text_area :comments %>
  </div>

  <%= f.fields_for :exercises do |ff| %>
    <%= render "exercise_fields", f: ff %>
  <% end %>

  <%= link_to_add_fields 'Add exercise', f, :exercises %>



  <div class="form-group">
    <%= f.submit %>
  </div>

<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#select_bodyareas input').on('change', function () {
      var selected = [];
      $('input:checked').each(function() {
          selected.push($(this).attr('value'));
      });

      $('.bodyarea').hide();

      for (i = 0; i < selected.length; i++) { 
        
        $('#bodyarea_'+ selected[i]).fadeIn(500);
      }
    });
  });
</script>

app/views/appointments/edit.html.erb
<%= link_to "Back to Appointments List", appointments_path, { class: "btn btn-default" } %>

<%= render 'form' %>

app/views/appointments/index.html.erb
<h1>Appointments</h1>

<p><%= link_to 'Create a new appointment', new_appointment_path, { class: "btn btn-info", role: "button" } %></p>

<div class="row">
  <div class="col-md-12">

    <%= month_calendar attribute: :app_date, events: @appointments do |date, apps| %>
      <p><%= date %></p>

      <% apps.each do |app| %>
        <%= link_to app.name, appointment_path(app) %>
      <% end %>
    <% end %>

  </div>
</div>

<div class="row">
  <div class="col-md-4">

    <h2>Appointment List</h2>
    <table class="table table-bordered">
     <thead>
        <th>Date</th>
        <th></th>
      </thead>
      <tbody>
        
        <% @appointments.each do |a| %>
          <tr>
            <td><%= link_to a.app_date.to_date, appointment_path(a) %></td>
            <td>  
              <%= link_to 'edit', edit_appointment_path(a) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/appointments/new.html.erb
<%= link_to 'Back to appointments list', appointments_path, { class: "btn btn-default", role: "button" } %>

<div class="row">
  <div class="col-md-8">
    <h3>Create a new Appointment</h3>
    <%= render 'form' %>
  </div>

</div>

app/views/appointments/show.html.erb
<%= link_to "Back to Appointments List", appointments_path %>

<h1>Appointment</h1>

<h5>Date: <%= @appointment.app_date.to_date %></h5>
<h5>Comments: <%= @appointment.comments %></h5>
<h5>Duration: <%= @appointment.duration %></h5>
<h3>Exercises</h3>

<% if @appointment.exercises.any? %>
  <% @appointment.exercises.each do |exercise| %>
    <div class="app_exercise">
      <% typeofexercise = Typesofexercise.find_by_id(exercise.typesofexercise_id) %>
      <%= image_tag typeofexercise.photo.url(:thumb) %>
      <h4><%= link_to typeofexercise.name, exercise_path(exercise) %></h4>
      <div class="exercise_text">Sets: <%= exercise.n_of_sets %></div>
      <div class="exercise_text">Repetitions: <%= exercise.n_of_repetitions %></div>
      <div class="exercise_text"><%= link_to 'edit', edit_exercise_path(exercise) %></div>
    </div>
  <% end %>
  <div style="clear: both">
  <p><%= link_to 'Edit Appointment', edit_appointment_path(@appointment), {class: "btn btn-link"} %></p>
<% else %>
  <%= flash.now[:error] = "There were no exercises in this appointment" %>
  <p><%= link_to 'edit', edit_appointment_path(@appointment) %></p>
<% end %>