config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :appointments
  resources :exercises
  resources :bodyareas
  resources :typesofexercises
  resources :reminders, only: [:new, :create, :destroy]

  root "static_pages#home"


end

app/models/bodyarea.rb
class Bodyarea < ActiveRecord::Base
  has_many :exercises

  has_many :typesofexercises

  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/controllers/bodyareas_controller.rb
class BodyareasController < ApplicationController
  before_action :find_bodyarea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  def index
    @bodyareas = Bodyarea.all
  end
  
  def show
  end

  def new
    @bodyarea = Bodyarea.new
  end

  def create
    @bodyarea = Bodyarea.new(bodyarea_params)

    if @bodyarea.save
      flash[:notice] = "The body area was created successfully!"

      redirect_to bodyareas_path
    else
      render :new
    end  
  end

  def edit
  end

  def update
    if @bodyarea.update(bodyarea_params)
      flash[:notice] = "The body area was updated successfully!"
    else
      render :edit
    end  
  end

  def destroy
    @bodyarea.delete

    redirect_to bodyareas_path
  end

  def find_bodyarea
    @bodyarea = Bodyarea.find_by_id(params[:id])
  end

  def bodyarea_params
    params.require(:bodyarea).permit(:name)
  end  
end  

app/views/bodyareas/_form.html.erb
<div class="col-md-4">
  <%= form_for @bodyarea do |b| %>
    
    <% if @bodyarea.errors.any? %>
      <h3><%= pluralize(@bodyarea.errors.count, "error") %> prohibited this bodyarea from being saved</h3>
      <ul>
        <% @bodyarea.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <div class="form-group">
      <%= b.label :name %>
      <%= b.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= b.submit %>
    </div>
  <% end %>
</div>

app/views/bodyareas/edit.html.erb
<%= link_to 'Back to Body Areas list', bodyareas_path, { class: "btn btn-default" } %>

<h1>Update <%= @bodyarea.name %></h1>

<%= render 'form' %>

app/views/bodyareas/index.html.erb
<h1>Body Areas</h1>

<% if current_user.is_admin? %>
  <p><%= link_to "Create new body area", new_bodyarea_path, { class: "btn btn-info", role: "button" } %></p>
<% end %>

<div class="row">
  <div class="col-md-4">
    <table class="table table-bordered">
      <thead>
        <th>Name</th>
        <% if current_user.is_admin? %>
          <th></th>
        <% end %>
      </thead>  
      <tbody>
        <% @bodyareas.each do |b| %>
          <tr>
            <td><%= b.name %></td>
            <% if current_user.is_admin? %>
              <td>
                <%= link_to 'edit', edit_bodyarea_path(b) %>
                <%= link_to 'delete', bodyarea_path(b), method: :delete, data: {confirm: "Are you sure you want to delete this Body Area?"} %>
              </td>
            <% end %>
          </tr>  
        <% end %> 
      </tbody>
    </table>
  </div>
</div>

app/views/bodyareas/new.html.erb
<%= link_to 'Back to Body Areas list', bodyareas_path %>

<h1>Create new Body Area</h1>

<%= render 'form' %>

app/views/bodyareas/show.html.erb
<h1><%= @bodyarea.name %></h1>

<p><%= @bodyarea.name %> exercises</p>

<ul>
  <% @bodyarea.typesofexercises.each do |exercise| %>
    <li><%= exercise.name %></li>
  <% end %>
<ul>
<%= link_to 'edit', edit_bodyarea_path(@bodyarea) %>