config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :appointments
  resources :exercises
  resources :bodyareas
  resources :typesofexercises
  resources :reminders, only: [:new, :create, :destroy]

  root "static_pages#home"


end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-style">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><span style="color: white; font-weight: bold">ManagePT</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user %>
        <ul class="nav navbar-nav nav-link-style">
          <li><a href="<%= root_path %>">Home<span class="sr-only">(current)</span></a></li>
          <li><a href="<%= appointments_path %>">Calendar</a></li>
          <% if current_user && (current_user.is_doctor? || current_user.is_admin?) %> 
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="<%= appointments_path %>">Appointments</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="<%= bodyareas_path %>">Body Areas</a></li>
                <li><a href="<%= exercises_path %>">Sets of Exercises</a></li>
                <li><a href="<%= typesofexercises_path %>">Exercises Types</a></li>
              </ul>
            </li>
          <% end %>
        </ul>
      <% end %>
      
      <ul class="nav navbar-nav navbar-right nav-link-style">
        <% if current_user %>
          <li><a href="<%= edit_user_registration_path %>"><%= current_user.email %></a></li>
        
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Options<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path  %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhysicalTherapyApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>

    <div class="container">      
      <% flash.each do |name, message| %>
        <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %>" >
           <%= message %> 
        </div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhysicalTherapyApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
      
      <% flash.each do |name, message| %>
        <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %>" >
           <%= message %> 
        </div>
      <% end %>

      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>